import { mkdirSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import YAML from "yaml";
import { assertSafeSlug } from "../paths.mjs";
import { loadWorkflow } from "../workflow.mjs";

function safeLaneId(itemId, index) {
  const raw = String(itemId || `item-${index + 1}`)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48);
  try {
    return assertSafeSlug(raw || `item-${index + 1}`, "lane id");
  } catch {
    return assertSafeSlug(`item-${index + 1}`, "lane id");
  }
}

function buildPrompt(item) {
  const criteria = (item.acceptance_criteria || [])
    .map((line) => `- ${line}`)
    .join("\n");
  return [
    item.objective,
    "",
    "Acceptance criteria:",
    criteria,
    "",
    `Plan reference: ${item.planning.plan_ref}`,
    `Source: ${item.source.ref}`,
    "Stay inside the declared lane scope. Do not commit or open a pull request.",
  ].join("\n");
}

function buildContext(items, cycleId) {
  const blocks = items.map((item) => [
    `### ${item.sourceKey}`,
    `- Objective: ${item.objective}`,
    `- Plan: ${item.planning.plan_ref}`,
    `- Scope: ${item.scope.join(", ")}`,
    `- Acceptance: ${item.acceptance_criteria.join("; ")}`,
    item.goal_refs?.length ? `- Goal refs: ${item.goal_refs.join(", ")}` : null,
  ].filter(Boolean).join("\n"));
  return [
    `# Director proposal context`,
    "",
    `Cycle: ${cycleId}`,
    "This packet was generated by a Director dry-run / proposal cycle.",
    "Master Dev launches the draft workflow with `agent-manager run … --detach`.",
    "",
    ...blocks,
    "",
  ].join("\n");
}

function buildWorkflowDocument({
  policy,
  items,
  cycleId,
  draftId,
}) {
  const workers = policy.workers || {};
  const harnessDefault = workers.harness_default || "claude";
  const modelDefault = workers.model_default || undefined;
  const repoName = basename(policy.repoRoot);
  const lanes = items.map((item, index) => {
    const lane = {
      id: safeLaneId(item.source.item_id, index),
      scope: item.scope.length === 1 ? item.scope[0] : item.scope,
      prompt: buildPrompt(item),
      kind: "implementation",
    };
    if (modelDefault) lane.model = modelDefault;
    return lane;
  });
  const goalRefs = [...new Set(items.flatMap((item) => item.goal_refs || []))];
  const reviewedPaths = [...new Set(items.flatMap((item) => [
    ...item.planning.reviewed_paths,
    ...item.scope,
  ]))];
  const instructionRefs = [...new Set(items.flatMap((item) =>
    item.planning.repository_instruction_refs))];
  const sourceRefs = [...new Set(items.map((item) => item.source.ref))];
  const primary = items[0];
  const document = {
    title: `Director proposal ${draftId}`,
    repo_shorthand: repoName,
    repo: policy.repoRoot,
    harness_default: harnessDefault,
    ...(modelDefault ? { model_default: modelDefault } : {}),
    base_ref: policy.repository.base_ref,
    claim_mode: "auto",
    integrate: items.length > 1,
    max_concurrency: Math.min(policy.autopilot.max_concurrency, lanes.length),
    policy: {
      allow_commit: false,
      allow_pr: false,
    },
    ...(goalRefs.length ? { goal_refs: goalRefs } : {}),
    planning: {
      source_refs: sourceRefs,
      plan_ref: items.length === 1
        ? primary.planning.plan_ref
        : `director-cycle:${cycleId}`,
      context: buildContext(items, cycleId),
      reviewed_base_sha: primary.repository.reviewed_base_sha,
      verified_by: primary.planning.verified_by,
      verified_at: primary.planning.verified_at,
      reviewed_paths: reviewedPaths,
      repository_instruction_refs: instructionRefs,
      attestations: {
        source_reviewed: true,
        repository_instructions_reviewed: true,
        relevant_code_reviewed: true,
        scope_verified: true,
      },
    },
    lanes,
  };
  return document;
}

function kickoffCommand(workflowPath) {
  return `agent-manager run ${JSON.stringify(workflowPath)} --detach`;
}

/**
 * Write one or more validated workflow drafts for the selected source items.
 * Prefer one multi-lane workflow when selected.length <= max_concurrency;
 * otherwise write one workflow per item.
 */
export function writeWorkflowDrafts({
  policy,
  selectedItems,
  cycleId,
  cycleDir,
}) {
  const workflowsDir = join(cycleDir, "workflows");
  mkdirSync(workflowsDir, { recursive: true, mode: 0o700 });
  if (!selectedItems.length) return [];

  const batches = selectedItems.length <= policy.autopilot.max_concurrency
    ? [selectedItems]
    : selectedItems.map((item) => [item]);

  const drafts = [];
  for (let index = 0; index < batches.length; index += 1) {
    const items = batches[index];
    const draftId = batches.length === 1
      ? "selected"
      : safeLaneId(items[0].source.item_id, index);
    const fileName = `${draftId}.yaml`;
    const path = join(workflowsDir, fileName);
    const document = buildWorkflowDocument({
      policy,
      items,
      cycleId,
      draftId,
    });
    writeFileSync(path, YAML.stringify(document), { encoding: "utf8", mode: 0o600 });
    let validateOk = false;
    let validateError = null;
    try {
      loadWorkflow(path, { repoOverride: policy.repoRoot });
      validateOk = true;
    } catch (error) {
      validateError = String(error?.message || error);
    }
    drafts.push({
      path,
      draftId,
      sourceKeys: items.map((item) => item.sourceKey),
      validateOk,
      ...(validateError ? { validateError } : {}),
      kickoff: kickoffCommand(path),
    });
  }
  return drafts;
}
